### ISSUE TITLE
Bot doesn't work over TLS

### ISSUE THREAD

**Issue by x89** [anlutro/botologist#62]
````
[2016-01-27 20:22:23,163] INFO - botologist.protocol.irc - Starting IRC client
[2016-01-27 20:22:23,163] INFO - botologist.protocol.irc - Connecting to irc.freenode.net:7000
[2016-01-27 20:22:23,163] DEBUG - botologist.protocol.irc - Looking up address info for irc.freenode.net:7000
[2016-01-27 20:22:23,210] DEBUG - botologist.protocol.irc - Trying to connect to 130.239.18.119:7000
[2016-01-27 20:22:23,733] INFO - botologist.protocol.irc - Successfully connected to server!
[2016-01-27 20:22:23,733] DEBUG - botologist.protocol.irc - SENDING: 'NICK the_dazzle'
[2016-01-27 20:22:23,733] DEBUG - botologist.protocol.irc - SENDING: 'USER dazz 0 * :dazz'
[2016-01-27 20:22:24,257] ERROR - botologist.protocol.irc - socket.recv threw an exception
Traceback (most recent call last):
  File "/home/napalm/botologist/botologist/protocol/irc.py", line 119, in loop
    data = self.irc_socket.recv()
  File "/home/napalm/botologist/botologist/protocol/irc.py", line 468, in recv
    data = self.socket.recv(bufsize)
ConnectionResetError: [Errno 104] Connection reset by peer
````

**Comment by anlutro** [comment]
You are banned from using my bot, you bloody moron
